version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: "dockerhub:dockerhub_user"
    DOCKER_PASSWORD: "dockerhub:dockerhub_password"
    

phases:
  pre_build:
    commands:
      - echo "$DOCKER_USERNAME"
      - echo "$HELLO"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - docker pull nginx:latest
      - docker tag nginx:latest gowthamshankar99/test_codebuild
      - docker push gowthamshankar/test_codebuild
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
