version: 0.2

env:
  secrets-manager:
    LOCAL_SECRET_VAR: "dockerhub:dockerhub_user"

phases:
  pre_build:
    commands:
      - echo "$LOCAL_SECRET_VAR"
      - echo "$HELLO"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...            
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
